export type AppIcon =
  | 'arrow-down-s-line'
  | 'arrow-left-s'
  | 'arrow-right-s-line'
  | 'check'
  | 'close-circle'
  | 'donut-chart'
  | 'download-cloud-2-line'
  | 'file-fill'
  | 'google-fill'
  | 'hand-coin'
  | 'moon-fill'
  | 'plus'
  | 'save'
  | 'shopping-basket-2'
  | 'sun-fill'
  | 'upload-cloud-2-line';
