#!/bin/sh

commit_msg_file=$(git rev-parse --git-path COMMIT_EDITMSG)
commit_msg=$(head -n1 "$commit_msg_file")

regex="^(fix|feat|chore|docs): [a-z].+$"

if ! echo "$commit_msg" | grep -Eq "$regex"; then
  echo "Commit message does not follow Conventional Commits format: <type>: <lowercase message>"
  echo "Allowed types: fix, feat, chore, docs"
  exit 1
fi
