name: Test

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

env:
  HUSKY: 0

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup repository
        uses: ./.github/workflows/actions/setup-repository

      - name: Setup ESLint cache
        uses: actions/cache@v5
        with:
          path: ./.eslintcache
          key: ${{ runner.os }}-eslint-${{ hashFiles('**/pnpm-lock.yaml', '**/eslint.config.mjs') }}

      - name: Run eslint
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test:unit

      - name: Build testing app
        run: pnpm build
        env:
          OCULAR_GENESIS_HOST: /api
          OCULAR_HYBRID_MODE: true

      - name: Build genesis
        run: go -C genesis build -v ./...

      - name: Test genesis
        run: go -C genesis test -v ./...
        
      - name: Prepare .env
        run: cp genesis/.env.example genesis/.env

      - name: Start genesis and ocular
        run: |
          pnpm dev:backend >genesis.log 2>&1 &
          pnpm vite preview >ocular.log 2>&1 &

      - name: Wait for genesis to be healthy
        uses: ./.github/workflows/actions/wait-for-health-check
        with:
          host: localhost:8080
          endpoint: health

      - name: Wait for ocular to be healthy
        uses: ./.github/workflows/actions/wait-for-health-check
        with:
          host: localhost:3000
          endpoint: dashboard

      - name: Install playwright browsers
        run: pnpm exec playwright install --with-deps firefox

      - name: Run e2e tests
        run: pnpm test:e2e

      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: test-results
          path: test-results/
          retention-days: 7

      - name: Upload service logs
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: service-logs
          path: "*.log"
          retention-days: 7
